from __future__ import annotations

from typing import Any


TYPE_MAP = {
    "string": "string",
    "integer": "int",
    "number": "double",
    "boolean": "bool",
}


def render_csharp_client(ir: dict[str, Any]) -> str:
    lines: list[str] = [
        "// Generated by tools/codegen/render_csharp_client.py",
        "// Do not edit manually.",
        "",
        "using System.Collections.Generic;",
        "using System.Net.Http;",
        "using System.Text.Json.Serialization;",
        "using System.Threading;",
        "using System.Threading.Tasks;",
        "using Max.Client.Runtime;",
        "",
        "namespace Max.Client.Generated;",
        "",
    ]

    for schema in ir.get("schemas", []):
        lines.extend(render_schema(schema))
        lines.append("")

    for operation in ir.get("operations", []):
        request_types = render_operation_request_types(operation)
        if request_types:
            lines.extend(request_types)
            lines.append("")

    lines.extend(
        [
            "public sealed class MaxBotApiClient : BaseApiClient",
            "{",
            "    public MaxBotApiClient(ClientConfig? config = null)",
            "        : base(config)",
            "    {",
            "    }",
            "",
        ]
    )

    operations = ir.get("operations", [])
    for index, operation in enumerate(operations):
        lines.extend(render_operation(operation, ir))
        if index != len(operations) - 1:
            lines.append("")

    lines.extend(
        [
            "}",
            "",
        ]
    )

    return "\n".join(lines)


def render_schema(schema: dict[str, Any]) -> list[str]:
    if schema.get("type") == "string" and schema.get("enum"):
        lines = [f"public enum {schema['name']}", "{"]
        for value in schema["enum"]:
            lines.append(f"    {pascal_case(value)},")
        lines.append("}")
        return lines

    if schema.get("type") != "object":
        return [f"public sealed class {schema['name']} {{ }}"]

    lines = [f"public sealed class {schema['name']}", "{"]
    properties = schema.get("properties", [])
    if not properties:
        lines.append("}")
        return lines

    for prop in properties:
        lines.append(f'    [JsonPropertyName("{prop["name"]}")]')
        lines.append(f"    public {map_property_to_csharp(prop)} {pascal_case(prop['name'])} {{ get; init; }}")
        lines.append("")

    if lines[-1] == "":
        lines.pop()
    lines.append("}")
    return lines


def render_operation_request_types(operation: dict[str, Any]) -> list[str]:
    if not operation_has_request(operation):
        return []

    lines: list[str] = []
    request_name = operation_request_type_name(operation)
    path_params = [param for param in operation.get("parameters", []) if param.get("in") == "path"]
    query_params = [param for param in operation.get("parameters", []) if param.get("in") == "query"]

    if path_params:
        lines.extend(
            [
                f"public sealed class {request_name}Path",
                "{",
            ]
        )
        for param in path_params:
            lines.append(f"    public {map_parameter_to_csharp(param)} {pascal_case(param['name'])} {{ get; init; }}")
            lines.append("")
        if lines[-1] == "":
            lines.pop()
        lines.append("}")
        lines.append("")

    if query_params:
        lines.extend(
            [
                f"public sealed class {request_name}Query",
                "{",
            ]
        )
        for param in query_params:
            lines.append(f"    public {map_parameter_to_csharp(param)} {pascal_case(param['name'])} {{ get; init; }}")
            lines.append("")
        if lines[-1] == "":
            lines.pop()
        lines.append("}")
        lines.append("")

    lines.extend(
        [
            f"public sealed class {request_name}",
            "{",
        ]
    )

    if path_params:
        lines.append(f"    public {request_name}Path Path {{ get; init; }} = new();")
    if query_params:
        lines.append(f"    public {request_name}Query Query {{ get; init; }} = new();")

    body_schema = resolve_request_body_schema(operation)
    if body_schema:
        lines.append(f"    public {body_schema} Body {{ get; init; }} = new();")

    lines.append("}")
    return lines


def render_operation(operation: dict[str, Any], ir: dict[str, Any]) -> list[str]:
    operation_name = pascal_case(operation["operation_id"])
    response_type = resolve_response_type(operation, ir) or "object"
    request_type = operation_request_type_name(operation)
    has_request = operation_has_request(operation)

    signature_args = "RequestOptions? options = null, CancellationToken cancellationToken = default"
    if has_request:
        signature_args = f"{request_type} request, RequestOptions? options = null, CancellationToken cancellationToken = default"

    lines = [
        f"    public Task<{response_type}?> {operation_name}Async({signature_args})",
        "    {",
        f"        return SendAsync<{response_type}>(new ApiRequest",
        "        {",
        f"            Method = HttpMethod.{http_method_name(operation['method'])},",
        f"            Path = {build_path_expression(operation.get('wire_path') or operation['path'], operation)},",
    ]

    query_expression = build_query_expression(operation)
    if query_expression:
        lines.append(f"            Query = {query_expression},")

    if operation.get("request_body"):
        lines.append("            Body = request.Body,")

    lines.extend(
        [
            "            Options = options,",
            "        }, cancellationToken);",
            "    }",
        ]
    )
    return lines


def build_path_expression(path: str, operation: dict[str, Any]) -> str:
    expression = path
    path_params = [p for p in operation.get("parameters", []) if p.get("in") == "path"]
    if not path_params:
        return quote_cs(path)

    for param in path_params:
        expression = expression.replace(
            "{" + param["name"] + "}",
            "{Uri.EscapeDataString(request.Path." + pascal_case(param["name"]) + ".ToString())}",
        )
    return f'$"{expression}"'


def build_query_expression(operation: dict[str, Any]) -> str | None:
    query_params = [param for param in operation.get("parameters", []) if param.get("in") == "query"]
    if not query_params:
        return None

    lines = ["new Dictionary<string, object?>", "            {"]
    for param in query_params:
        lines.append(f'                ["{param["name"]}"] = request.Query.{pascal_case(param["name"])},')
    lines.append("            }")
    return "\n".join(lines)


def resolve_response_type(operation: dict[str, Any], ir: dict[str, Any]) -> str | None:
    schema_names = {schema["name"] for schema in ir.get("schemas", [])}
    for response in operation.get("responses", []):
        if response.get("status_code") != "200":
            continue
        for media_type in response.get("media_types", []):
            schema_ref = media_type.get("schema_ref")
            if not schema_ref:
                continue
            schema_name = schema_ref.rsplit("/", 1)[-1]
            if schema_name in schema_names:
                return schema_name
    return None


def resolve_request_body_schema(operation: dict[str, Any]) -> str | None:
    request_body = operation.get("request_body") or {}
    for media_type in request_body.get("media_types", []):
        schema_ref = media_type.get("schema_ref")
        if schema_ref:
            return schema_ref.rsplit("/", 1)[-1]
    return None


def operation_request_type_name(operation: dict[str, Any]) -> str:
    return f"{pascal_case(operation['operation_id'])}Params"


def operation_has_request(operation: dict[str, Any]) -> bool:
    return bool(operation.get("parameters")) or bool(operation.get("request_body"))


def map_property_to_csharp(prop: dict[str, Any]) -> str:
    base_type = map_node_type_to_csharp(prop)
    if not prop.get("required") and base_type in {"int", "double", "bool"}:
        return f"{base_type}?"
    if not prop.get("required") and base_type != "string" and not base_type.endswith("?") and not base_type.startswith("List<"):
        return f"{base_type}?"
    if not prop.get("required") and (base_type == "string" or base_type.startswith("List<")) and not base_type.endswith("?"):
        return f"{base_type}?"
    if prop.get("nullable") and not base_type.endswith("?"):
        return f"{base_type}?"
    return base_type


def map_parameter_to_csharp(parameter: dict[str, Any]) -> str:
    base_type = map_node_type_to_csharp(parameter)
    if not parameter.get("required") and base_type in {"int", "double", "bool"}:
        return f"{base_type}?"
    if not parameter.get("required") and base_type == "string":
        return "string?"
    return base_type


def map_node_type_to_csharp(node: dict[str, Any]) -> str:
    if node.get("ref"):
        return node["ref"].rsplit("/", 1)[-1]
    if node.get("type") == "array":
        return f"List<{map_array_item_to_csharp(node)}>"
    return TYPE_MAP.get(node.get("type"), "object")


def map_array_item_to_csharp(node: dict[str, Any]) -> str:
    if node.get("items_ref"):
        return node["items_ref"].rsplit("/", 1)[-1]
    return TYPE_MAP.get(node.get("items_type"), "object")


def http_method_name(method: str) -> str:
    mapping = {
        "get": "Get",
        "post": "Post",
        "put": "Put",
        "patch": "Patch",
        "delete": "Delete",
    }
    return mapping[method]


def pascal_case(value: str) -> str:
    tokens = value.replace("-", "_").split("_")
    return "".join(token[:1].upper() + token[1:] for token in tokens if token)


def quote_cs(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
