from __future__ import annotations

import keyword
from typing import Any


TYPE_MAP = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
}


def safe_python_name(value: str) -> str:
    if keyword.iskeyword(value):
        return f"{value}_"
    return value


def render_python_client(ir: dict[str, Any]) -> str:
    lines: list[str] = [
        "# Generated by tools/codegen/render_python_client.py",
        "# Do not edit manually.",
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal, NotRequired, TypedDict, TypeAlias",
        "from urllib.parse import quote",
        "",
        "from ..runtime import BaseApiClient, ClientConfig, RequestOptions",
        "",
    ]

    for schema in ir.get("schemas", []):
        lines.extend(render_schema(schema))
        lines.append("")

    for operation in ir.get("operations", []):
        request_typed_dict = render_operation_request_typed_dict(operation)
        if request_typed_dict:
            lines.extend(request_typed_dict)
            lines.append("")

    lines.extend(
        [
            "class MaxBotApiClient(BaseApiClient):",
            "    def __init__(self, config: ClientConfig | None = None) -> None:",
            "        super().__init__(config=config)",
        ]
    )

    operations = ir.get("operations", [])
    if operations:
        lines.append("")

    for index, operation in enumerate(operations):
        lines.extend(render_operation(operation, ir))
        if index != len(operations) - 1:
            lines.append("")

    lines.append("")
    return "\n".join(lines)


def render_schema(schema: dict[str, Any]) -> list[str]:
    if schema.get("type") == "string" and schema.get("enum"):
        variants = ", ".join(quote_py(value) for value in schema["enum"])
        return [f"{schema['name']}: TypeAlias = Literal[{variants}]"]

    if schema.get("type") != "object":
        return [f"{schema['name']}: TypeAlias = {map_scalar_type(schema)}"]

    lines = [f"class {schema['name']}(TypedDict, total=False):"]
    properties = schema.get("properties", [])
    if not properties:
        lines.append("    pass")
        return lines

    for prop in properties:
        prop_type = map_property_to_python(prop)
        prop_name = safe_python_name(prop["name"])
        if prop.get("required"):
            lines.append(f"    {prop_name}: {prop_type}")
        else:
            lines.append(f"    {prop_name}: NotRequired[{prop_type}]")

    return lines


def render_operation_request_typed_dict(operation: dict[str, Any]) -> list[str]:
    if not operation_has_request(operation):
        return []

    emitted = False
    lines: list[str] = []
    main_fields: list[str] = []

    path_params = [param for param in operation.get("parameters", []) if param.get("in") == "path"]
    query_params = [param for param in operation.get("parameters", []) if param.get("in") == "query"]

    if path_params:
        path_name = f"{operation_request_type_name(operation)}Path"
        lines.append(f"class {path_name}(TypedDict):")
        for param in path_params:
            lines.append(f"    {safe_python_name(param['name'])}: {map_parameter_to_python(param)}")
        lines.append("")
        main_fields.append(f"    path: {path_name}")
        emitted = True

    if query_params:
        query_name = f"{operation_request_type_name(operation)}Query"
        lines.append(f"class {query_name}(TypedDict, total=False):")
        for param in query_params:
            lines.append(f"    {safe_python_name(param['name'])}: {map_parameter_to_python(param)}")
        lines.append("")
        main_fields.append(f"    query: {query_name}")
        emitted = True

    body_schema = resolve_request_body_schema(operation)
    if body_schema:
        main_fields.append(f"    body: {body_schema}")
        emitted = True

    if not emitted:
        return []

    lines.append(f"class {operation_request_type_name(operation)}(TypedDict, total=False):")
    lines.extend(main_fields or ["    pass"])
    return lines


def render_operation(operation: dict[str, Any], ir: dict[str, Any]) -> list[str]:
    operation_name = operation["operation_id"]
    response_type = resolve_response_type(operation, ir) or "dict[str, Any]"
    has_request = operation_has_request(operation)
    args = "options: RequestOptions | None = None"
    if has_request:
        args = f"request: {operation_request_type_name(operation)}, options: RequestOptions | None = None"

    lines = [
        f"    def {operation_name}(self, {args}) -> {response_type}:",
        f"        return self.request(",
        f"            method={quote_py(operation['method'].upper())},",
        f"            path={build_path_expression(operation.get('wire_path') or operation['path'], operation)},",
    ]

    query_expression = build_query_expression(operation)
    if query_expression:
        lines.append(f"            query={query_expression},")

    if operation.get("request_body"):
        lines.append("            body=request['body'],")

    lines.extend(
        [
            "            options=options,",
            "        )",
        ]
    )

    return lines


def build_path_expression(path: str, operation: dict[str, Any]) -> str:
    path_params = [p for p in operation.get("parameters", []) if p.get("in") == "path"]
    if not path_params:
        return quote_py(path)

    expression = path
    for param in path_params:
        placeholder = "{" + param["name"] + "}"
        replacement = '{quote(str(request["path"]["' + safe_python_name(param["name"]) + '"]), safe="")}'
        expression = expression.replace(placeholder, replacement)

    return f"f{quote_py(expression)}"


def build_query_expression(operation: dict[str, Any]) -> str | None:
    query_params = [param for param in operation.get("parameters", []) if param.get("in") == "query"]
    if not query_params:
        return None

    parts = [
        f"{quote_py(param['name'])}: request['query'].get({quote_py(safe_python_name(param['name']))})"
        for param in query_params
    ]
    return "{ " + ", ".join(parts) + " }"


def operation_request_type_name(operation: dict[str, Any]) -> str:
    return f"{operation['operation_id'][0].upper()}{operation['operation_id'][1:]}Params"


def operation_has_request(operation: dict[str, Any]) -> bool:
    return bool(operation.get("parameters")) or bool(operation.get("request_body"))


def resolve_response_type(operation: dict[str, Any], ir: dict[str, Any]) -> str | None:
    schema_names = {schema["name"] for schema in ir.get("schemas", [])}

    for response in operation.get("responses", []):
        if response.get("status_code") != "200":
            continue

        for media_type in response.get("media_types", []):
            schema_ref = media_type.get("schema_ref")
            if not schema_ref:
                continue

            schema_name = schema_ref.rsplit("/", 1)[-1]
            if schema_name in schema_names:
                return schema_name

    return None


def resolve_request_body_schema(operation: dict[str, Any]) -> str | None:
    request_body = operation.get("request_body") or {}
    for media_type in request_body.get("media_types", []):
        schema_ref = media_type.get("schema_ref")
        if schema_ref:
            return schema_ref.rsplit("/", 1)[-1]

        schema_type = media_type.get("schema_type")
        if schema_type:
            return TYPE_MAP.get(schema_type, "Any")

    return None


def map_property_to_python(prop: dict[str, Any]) -> str:
    if prop.get("ref"):
        return prop["ref"].rsplit("/", 1)[-1]

    if prop.get("type") == "array":
        return f"list[{map_array_items_to_python(prop)}]"

    if prop.get("enum"):
        variants = ", ".join(quote_py(value) for value in prop["enum"])
        return f"Literal[{variants}]"

    scalar_type = TYPE_MAP.get(prop.get("type"), "Any")
    if prop.get("nullable"):
        return f"{scalar_type} | None"
    return scalar_type


def map_parameter_to_python(parameter: dict[str, Any]) -> str:
    if parameter.get("ref"):
        return parameter["ref"].rsplit("/", 1)[-1]

    if parameter.get("type") == "array":
        return f"list[{map_array_items_to_python(parameter)}]"

    if parameter.get("enum"):
        variants = ", ".join(quote_py(value) for value in parameter["enum"])
        return f"Literal[{variants}]"

    return TYPE_MAP.get(parameter.get("type"), "Any")


def map_array_items_to_python(node: dict[str, Any]) -> str:
    if node.get("items_ref"):
        return node["items_ref"].rsplit("/", 1)[-1]

    return TYPE_MAP.get(node.get("items_type"), "Any")


def map_scalar_type(schema: dict[str, Any]) -> str:
    if schema.get("enum"):
        variants = ", ".join(quote_py(value) for value in schema["enum"])
        return f"Literal[{variants}]"
    return TYPE_MAP.get(schema.get("type"), "Any")


def quote_py(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"
