from __future__ import annotations

from typing import Any


TYPE_MAP = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
}


def render_typescript_client(ir: dict[str, Any]) -> str:
    lines: list[str] = []

    lines.extend(
        [
            "// Generated by tools/codegen/render_typescript_client.py",
            "// Do not edit manually.",
            "",
        ]
    )

    for schema in ir.get("schemas", []):
        lines.extend(render_schema(schema))
        lines.append("")

    lines.extend(render_http_types())
    lines.append("")

    class_name = "MaxBotApiClient"
    default_base_url = ir["api"]["servers"][0] if ir["api"]["servers"] else ""

    lines.extend(
        [
            f"export class {class_name} {{",
            "  constructor(",
            f"    private readonly baseUrl: string = {quote(default_base_url)}",
            "  ) {}",
        ]
    )

    operations = ir.get("operations", [])
    if operations:
        lines.append("")

    for index, operation in enumerate(operations):
        lines.extend(render_operation(operation, ir))
        if index != len(operations) - 1:
            lines.append("")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_schema(schema: dict[str, Any]) -> list[str]:
    lines = [f"export interface {schema['name']} {{"]

    for prop in schema.get("properties", []):
        optional_marker = "?" if not prop.get("required") else ""
        ts_type = map_property_to_ts(prop)
        lines.append(f"  {prop['name']}{optional_marker}: {ts_type};")

    lines.append("}")
    return lines


def render_http_types() -> list[str]:
    return [
        "export interface RequestOptions {",
        "  signal?: AbortSignal;",
        "  headers?: Record<string, string>;",
        "}",
    ]


def render_operation(operation: dict[str, Any], ir: dict[str, Any]) -> list[str]:
    method = operation["method"].upper()
    path = operation["path"]
    operation_name = operation["operation_id"]
    response_type = resolve_response_type(operation, ir) or "unknown"

    return [
        f"  async {operation_name}(options: RequestOptions = {{}}): Promise<{response_type}> {{",
        "    const response = await fetch(",
        f"      `${{this.baseUrl}}{path}`,",
        "      {",
        f"        method: {quote(method)},",
        "        headers: {",
        "          'Content-Type': 'application/json',",
        "          ...(options.headers ?? {}),",
        "        },",
        "        signal: options.signal,",
        "      }",
        "    );",
        "",
        "    if (!response.ok) {",
        f"      throw new Error(`{operation_name} failed with status ${{response.status}}`);",
        "    }",
        "",
        f"    return (await response.json()) as {response_type};",
        "  }",
    ]


def resolve_response_type(operation: dict[str, Any], ir: dict[str, Any]) -> str | None:
    schema_names = {schema["name"] for schema in ir.get("schemas", [])}

    for response in operation.get("responses", []):
        if response.get("status_code") != "200":
            continue

        for media_type in response.get("media_types", []):
            schema_ref = media_type.get("schema_ref")
            if not schema_ref:
                continue

            schema_name = schema_ref.rsplit("/", 1)[-1]
            if schema_name in schema_names:
                return schema_name

    return None


def map_property_to_ts(prop: dict[str, Any]) -> str:
    if prop.get("ref"):
        return prop["ref"].rsplit("/", 1)[-1]

    ts_type = TYPE_MAP.get(prop.get("type"), "unknown")
    if prop.get("nullable"):
        return f"{ts_type} | null"
    return ts_type


def quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"
