from __future__ import annotations

from typing import Any


TYPE_MAP = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
}


def render_typescript_client(ir: dict[str, Any]) -> str:
    lines: list[str] = []

    lines.extend(
        [
            "// Generated by tools/codegen/render_typescript_client.py",
            "// Do not edit manually.",
            "",
            "import { BaseApiClient, type ClientConfig, type RequestOptions } from '../runtime/index.js';",
            "",
        ]
    )

    for schema in ir.get("schemas", []):
        lines.extend(render_schema(schema))
        lines.append("")

    for operation in ir.get("operations", []):
        request_interface = render_operation_request_interface(operation)
        if request_interface:
            lines.extend(request_interface)
            lines.append("")

    class_name = "MaxBotApiClient"

    lines.extend(
        [
            f"export class {class_name} extends BaseApiClient {{",
            "  constructor(config: ClientConfig = {}) {",
            "    super(config);",
            "  }",
        ]
    )

    operations = ir.get("operations", [])
    if operations:
        lines.append("")

    for index, operation in enumerate(operations):
        lines.extend(render_operation(operation, ir))
        if index != len(operations) - 1:
            lines.append("")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_schema(schema: dict[str, Any]) -> list[str]:
    if schema.get("type") == "string" and schema.get("enum"):
        variants = " | ".join(quote(value) for value in schema["enum"])
        return [f"export type {schema['name']} = {variants};"]

    lines = [f"export interface {schema['name']} {{"]

    for prop in schema.get("properties", []):
        optional_marker = "?" if not prop.get("required") else ""
        ts_type = map_property_to_ts(prop)
        lines.append(f"  {prop['name']}{optional_marker}: {ts_type};")

    lines.append("}")
    return lines


def render_operation(operation: dict[str, Any], ir: dict[str, Any]) -> list[str]:
    method = operation["method"].upper()
    operation_name = operation["operation_id"]
    response_type = resolve_response_type(operation, ir) or "unknown"
    request_type = operation_request_type_name(operation)
    has_request = operation_has_request(operation)
    args = "options: RequestOptions = {}"
    if has_request:
        args = f"request: {request_type}, options: RequestOptions = {{}}"

    lines = [
        f"  async {operation_name}({args}): Promise<{response_type}> {{",
        f"    return this.request<{response_type}>({{",
        f"      method: {quote(method)},",
        f"      path: {build_path_expression(operation['path'], operation)},",
    ]

    query_expression = build_query_expression(operation)
    if query_expression:
        lines.append(f"      query: {query_expression},")

    if operation.get("request_body"):
        lines.append("      body: request.body,")

    lines.extend(
        [
            "      options,",
            "    });",
            "  }",
        ]
    )
    return lines


def resolve_response_type(operation: dict[str, Any], ir: dict[str, Any]) -> str | None:
    schema_names = {schema["name"] for schema in ir.get("schemas", [])}

    for response in operation.get("responses", []):
        if response.get("status_code") != "200":
            continue

        for media_type in response.get("media_types", []):
            schema_ref = media_type.get("schema_ref")
            if not schema_ref:
                continue

            schema_name = schema_ref.rsplit("/", 1)[-1]
            if schema_name in schema_names:
                return schema_name

    return None


def map_property_to_ts(prop: dict[str, Any]) -> str:
    if prop.get("ref"):
        return prop["ref"].rsplit("/", 1)[-1]

    if prop.get("type") == "array":
        return f"{map_array_items_to_ts(prop)}[]"

    if prop.get("enum"):
        return " | ".join(quote(value) for value in prop["enum"])

    ts_type = TYPE_MAP.get(prop.get("type"), "unknown")
    if prop.get("nullable"):
        return f"{ts_type} | null"
    return ts_type


def map_parameter_to_ts(parameter: dict[str, Any]) -> str:
    if parameter.get("ref"):
        return parameter["ref"].rsplit("/", 1)[-1]

    if parameter.get("type") == "array":
        return f"{map_array_items_to_ts(parameter)}[]"

    if parameter.get("enum"):
        return " | ".join(quote(value) for value in parameter["enum"])

    return TYPE_MAP.get(parameter.get("type"), "unknown")


def map_array_items_to_ts(node: dict[str, Any]) -> str:
    if node.get("items_ref"):
        return node["items_ref"].rsplit("/", 1)[-1]

    return TYPE_MAP.get(node.get("items_type"), "unknown")


def render_operation_request_interface(operation: dict[str, Any]) -> list[str]:
    if not operation_has_request(operation):
        return []

    lines = [f"export interface {operation_request_type_name(operation)} {{"]

    path_params = [param for param in operation.get("parameters", []) if param.get("in") == "path"]
    query_params = [param for param in operation.get("parameters", []) if param.get("in") == "query"]

    if path_params:
        lines.append("  path: {")
        for param in path_params:
            optional_marker = "" if param.get("required") else "?"
            lines.append(f"    {param['name']}{optional_marker}: {map_parameter_to_ts(param)};")
        lines.append("  };")

    if query_params:
        lines.append("  query: {")
        for param in query_params:
            optional_marker = "" if param.get("required") else "?"
            lines.append(f"    {param['name']}{optional_marker}: {map_parameter_to_ts(param)};")
        lines.append("  };")

    body_schema = resolve_request_body_schema(operation)
    if body_schema:
        optional_marker = "" if (operation.get("request_body") or {}).get("required") else "?"
        lines.append(f"  body{optional_marker}: {body_schema};")

    lines.append("}")
    return lines


def render_query_params(operation: dict[str, Any]) -> list[str]:
    return []


def operation_request_type_name(operation: dict[str, Any]) -> str:
    return f"{operation['operation_id'][0].upper()}{operation['operation_id'][1:]}Params"


def operation_has_request(operation: dict[str, Any]) -> bool:
    return bool(operation.get("parameters")) or bool(operation.get("request_body"))


def build_path_expression(path: str, operation: dict[str, Any]) -> str:
    expression = path
    for param in [p for p in operation.get("parameters", []) if p.get("in") == "path"]:
        placeholder = "{" + param["name"] + "}"
        replacement = "${encodeURIComponent(String(request.path." + param["name"] + "))}"
        expression = expression.replace(placeholder, replacement)
    return f"`{expression}`"


def build_query_expression(operation: dict[str, Any]) -> str | None:
    query_params = [param for param in operation.get("parameters", []) if param.get("in") == "query"]
    if not query_params:
        return None

    parts = [f"{param['name']}: request.query.{param['name']}" for param in query_params]
    return "{ " + ", ".join(parts) + " }"


def resolve_request_body_schema(operation: dict[str, Any]) -> str | None:
    request_body = operation.get("request_body") or {}
    for media_type in request_body.get("media_types", []):
        schema_ref = media_type.get("schema_ref")
        if schema_ref:
            return schema_ref.rsplit("/", 1)[-1]

        schema_type = media_type.get("schema_type")
        if schema_type:
            return TYPE_MAP.get(schema_type, "unknown")

    return None


def quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"
